### ISSUE TITLE
非字幕建议和请求

### ISSUE THREAD

**Issue by jiahe224** [GitHubDaily/ChatGPT-Prompt-Engineering-for-Developers-in-Chinese#1]
1.建议：将视频放入合集，否则第一集播完会播其它的，除非进你主页去看。
2.请求：提供一个notebook的网盘链接

**Comment by YSoer** [comment]
1. 复制下方链接到新窗口打开：

https://www.bilibili.com/list/15467823?sid=3247315

2. Notebook 已经有人开源了：

https://github.com/datawhalechina/prompt-engineering-for-developers
